title: OK Anki Decks
description: Study guides, flashcards, and resources
remote_theme: just-the-docs/just-the-docs
# Optional tweaks
color_scheme: dark
aux_links:
  "OKAnkiDecks on GitHub":
    - "//github.com/oskarkerimbaev/OKAnkiDecks/"
search_enabled: false
